### ISSUE TITLE
Can I get a validation pesq data?

### ISSUE THREAD

**Issue by Outerskyb** [winddori2002/MANNER#5]
Hi
First of all, I approciate with this great job you did.

Now I'm training your model with a little modifing.
The problem is validation pesq is lower than my expectation (epoch128/pesq 2.78)

I know in your experiment final epoch was 300. That may means my work is not trained enough.
And I need few more days to reach 300.
But If I can get validation pesq data for each epochs, I can check the learning is going well or not.

thanks

**Comment by winddori2002** [comment]
Hi,

If you are using the VoiceBank-DEMAND dataset, the validation pesq would be about 2.86~2.90. 
This is because the training setting of the public VoiceBank-DEMAND dataset is made under more difficult conditions.
And when the validation score reached the score as I mentioned above, the test pesq will be similar to the score as the paper showed.

Thank you

**Comment by Outerskyb** [comment]
Thank you

**Comment by dxxxmmm** [comment]
> Hi First of all, I approciate with this great job you did.
> 
> Now I'm training your model with a little modifing. The problem is validation pesq is lower than my expectation (epoch128/pesq 2.78)
> 
> I know in your experiment final epoch was 300. That may means my work is not trained enough. And I need few more days to reach 300. But If I can get validation pesq data for each epochs, I can check the learning is going well or not.
> 
> thanks

Hi，could you tell me how you trained it? I encountered the following error when trying to reproduce it.  FileNotFoundError: Project root directory not found. Indicators: ['.project-root']
