### ISSUE TITLE
customized evaluation

### ISSUE THREAD

**Issue by catalwaysright** [winddori2002/MANNER#7]
Hi! Is it possible to input our own audio and get the enhanced audio through the model?

**Comment by winddori2002** [comment]
Hi!

We have uploaded the code for custom enhancement.
You can find details in './custom_enhance.py'.
The code is only for inference, and if you want to evaluate, you can refer to './eval_measure.py'.

Thanks for your interest.

**Comment by falseywinchnet** [comment]
Hi! I have adapted manner into a custom audio processing demo. 
[demo.py.txt](https://github.com/winddori2002/MANNER/files/9539530/demo.py.txt)
attached is the source code. 

Because I dont really understand how manner works I have fed it only 1 or 2 seconds at a time of audio
also because my script wont allow for a greater delay

manner, as other networks and methods of noise gating, only has a short term memory(seemingly) for variations in 
amplitude(as in a noise gate approach) and cannot(as used here) significantly attenuate noise outside of windows of activity
